---
name: module3_task0

"on":
  push:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Setup
        run: ./module3_task1/setup.sh

      - name: Run Make Build
        run: cd module3_task1/ && make build && make lint

      - name: Run the application
        run: cd module3_task1/ && make run

      - name: Create a new blog post
        run: cd module3_task1/ && make post

      - name: Stop the application
        run: cd module3_task1/ && make stop

      - name: Clean
        run: cd module3_task1/ && make clean
